export const GET_LOGO = "GET_LOGO";
export const GETTING_FIRST_TREE_WELCOME_MESSAGES =
  "GETTING_FIRST_TREE_WELCOME_MESSAGES";
export const GETTING_FIRST_NODE_OPTIONS = "GETTING_FIRST_NODE_OPTIONS";
export const GETTING_ALL_NODE_MESSAGES = "GETTING_ALL_NODE_MESSAGES";
export const GETTING_NODE_OPTIONS = "GETTING_NODE_OPTIONS";


